### PR TITLE
frontend project skeleton and how to run instructions

### PR DESCRIPTION
**Pull request by jbuddha**
I have created a vue project using npm

### CODE REVIEW

**Comment by vinaypuppal** [comment]
Consider this comment before merging this https://github.com/coderplex/OpenRank/issues/18#issuecomment-335404942

**Comment by jbuddha** [comment]
@vinaypuppal, we can add these even at later point, can't we?

**Comment by vinaypuppal** [comment]
@jbuddha No we cant integrate Nuxt.js at later point because its totally different from vue-cli webpack template you used for creating this skeleton. And Yes we can migrate later but the point of using nuxt.js now is to eliminate all these webpack configs and router configs which we have to do manually and allow nuxt.js to do it for us with some additional benefits it offers like server-side rendering and automatic code splitting ..etc

**Comment by jbuddha** [comment]
@vinaypuppal if you also want to contribute we can certainly use those frameworks; Because none of us has used those frameworks, we would need someone who used those frameworks for some time.

**Comment by vinaypuppal** [comment]
@jbuddha Yeah sure I can help and contribute.

**Pull request merged**
